# -*- coding: utf-8 -*-
"""Malaria Detection App

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eOafISQwrRBMtmnZP1HCn5vVG5OoinTm
"""

import streamlit as st

